spring:
  application:
    name: cadastro-empresa

  kafka:

    bootstrap-servers: kafka:9092

    consumer:
      group-id: grupo-empresa
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://postgres-db:5432/cadastro_empresa

    username: postgres
    password: 123456

  jpa:
    open-in-view: false


    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    config:
      enabled: false

  docker:
    compose:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8081

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
topic:
  empresa-evento: empresa.cadastro.evento
logging:
  level:
    com.netflix.discovery: DEBUG